version: '3.3'
services:
  client1:
    build: ./client1
    links:
      - server
    ports:
      - "5001:22"
    volumes:
      - ./client1:/home
  client2:
    build: ./client2
    links:
      - server
    ports:
      - "5002:22"
    volumes:
      - ./client2:/home
  server:
    build: ./server
    volumes:
      - ./server:/home
    ports:
      - "5000:22"